# setting tmux prefix key
set -g prefix C-t
bind-key C-t send-prefix
unbind-key C-b

# enable mouse control
setw -g mouse
#set-option -g mouse on

# clipboard related key binding
set -s copy-command "xsel --clipboard --input"
# disable copy-pipe for conpetition
set -s set-clipboard off
bind-key -T copy-mode-vi C-m send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel
#bind-key p run "xsel -o | tmux load-buffer - ; tmux paste-buffer"

# toggle synchronize-panes option
bind a setw synchronize-panes \; display "synchronize-panes #{?pane_synchronized,on,off}"

# create new session on current directory
bind c new-window -c "#{pane_current_path}"

# launch fzv command in mouse mode
bind-key -n TripleClick1Pane send-keys "fzv -m" C-m

# status style
set-option -g status-style "fg=white,bg=green"
set -g window-status-current-style "fg=white,bg=black"
set -g window-status-style "fg=white,bg=green"

# pane border style
set -g pane-border-lines heavy
set-option -g pane-active-border-style fg=green,bg=default
set-option -g pane-border-style fg=green,bg=default

# pane split keybind
bind v split-window -v
bind h split-window -h

# pane sizing keybind
bind < resize-pane -L 1
bind > resize-pane -R 1
bind - resize-pane -D 1
bind + resize-pane -U 1

# active window color
set-option -g window-active-style 'bg=black'
# inactive window color
set-option -g window-style 'bg=#444444'

# display current datetime on status bar
set-option -g status-right '%Y-%m-%d(%a) %H:%M:%S'

# history length
set-option -g history-limit 10000

# pane number displaying time
set -g display-panes-time 3000

# reload tmux
bind C-r 'source-file ~/.tmux.conf ; display-message "reloaded"'
